project:
  type: website
  output-dir: docs

website:
  title: "Quarto yml name"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resources.qmd
        text: NewTab
      - about.qmd

format:
  html:
    theme:
      - minty
    css: styles.css
    toc: true



